name: Build GDExtension

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_call:
    inputs:
      extension-name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # A build is made for every possible combination of parameters
        # You can add or remove entries from the arrays of each parameter to customize which builds you want to run
        # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
        target:
          [
            { platform: linux, arch: x86_64, os: ubuntu-22.04, flags: "" },
            { platform: linux, arch: arm64, os: ubuntu-22.04-arm, flags: "" },
            { platform: windows, arch: x86_64, os: windows-latest, flags: "" },
            { platform: windows, arch: arm64, os: windows-latest, flags: "" },
            { platform: macos, arch: universal, os: macos-latest, flags: '-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"' },
            { platform: android, arch: x86_64, os: ubuntu-22.04, flags: '-DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake" -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21' },
            { platform: android, arch: arm64, os: ubuntu-22.04, flags: '-DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake" -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21' },
            { platform: ios, arch: arm64, os: macos-latest, flags: "-DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_SYSROOT=iphoneos" },
          ]
        target-type: [template_debug, template_release]
        float-precision: [single]

    runs-on: ${{ matrix.target.os }}
    defaults:
      run:
        shell: ${{ matrix.target.platform == 'windows' && 'msys2 {0}' || 'bash' }}

    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch godot-cpp submodule
        shell: bash
        run: |
          git submodule update --init --recursive --depth 1 godot-cpp

      # Setup the compiler environment specifically for Windows/MSVC
      - name: Setup MSYS2
        if: ${{ matrix.target.platform == 'windows' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64 # Modern 64-bit Windows environment
          path-type: inherit
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      # Select Xcode version for iOS
      - name: Setup Xcode Environment (iOS only)
        if: ${{ matrix.target.platform == 'ios' }}
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcrun --sdk iphoneos --show-sdk-path

      # Build GDExtension (with caches)

      - name: Setup Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
          variant: sccache # Required for MSVC/Windows compiler caching tracking

      - name: Configure CMake
        #shell: uses default
        run: |
          # Map Godot's build types (template, debug, release_debug) to CMake configurations
          if [ "${{ matrix.target-type }}" = "template_release" ]; then
            BUILD_TYPE="Release"
          else
            BUILD_TYPE="Debug"
          fi
          
          cmake -G Ninja -B build -S . \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache \
            -DGD_ARCH=${{ matrix.target.arch }} \
            -DGD_PRECISION=${{ matrix.float-precision }} \
             ${{ matrix.target.flags }}

      - name: Build GDExtension via CMake
        #shell: uses default
        run: |
          if [ "${{ matrix.target-type }}" = "template_release" ]; then
            BUILD_TYPE="Release"
          else
            BUILD_TYPE="Debug"
          fi

          cmake --build build \
          --config $BUILD_TYPE \
          --target ${{ inputs.extension-name }} \

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.extension-name }}-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            extensions/${{ inputs.extension-name }}}/bin/*.gdextension
            build/bin/${{ inputs.extension-name }}/**/*.dll
            build/bin/${{ inputs.extension-name }}/**/*.so
            build/bin/${{ inputs.extension-name }}/**/*.dylib
            build/bin/${{ inputs.extension-name }}/**/*.pdb

  # Merges all the build artifacts together into a single artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v6
        with:
          name: ${{ inputs.extension-name }}
          pattern: ${{ inputs.extension-name }}-*
          delete-merged: true
