name: Build Terrain GDExtension 

on:
  workflow_call:
  push:
    paths:
      - 'extensions/terrain/**'
      - '.github/workflows/**'
  pull_request:
      paths:
      - 'extensions/terrain/**'
      - '.github/workflows/**'
  merge_group:

defaults: 
  run: 
    working-directory: extensions/terrain
    
permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # A build is made for every possible combination of parameters
        # You can add or remove entries from the arrays of each parameter to customize which builds you want to run
        # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
        target:
          [
            #{ platform: linux, arch: x86_64, os: ubuntu-22.04, flags: "" },
            #{ platform: linux, arch: arm64, os: ubuntu-22.04-arm, flags: "" },
            { platform: windows, arch: x86_64, os: windows-latest, flags: "-A x64" },
            #{ platform: windows, arch: arm64, os: windows-latest, flags: "-A ARM64" },
            #{ platform: macos, arch: universal, os: macos-latest, flags: '-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"' },
            #{ platform: android, arch: x86_64, os: ubuntu-22.04, flags: '-DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake" -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21' },
            #{ platform: android, arch: arm64, os: ubuntu-22.04, flags: '-DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake" -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21' },
            #{ platform: ios, arch: arm64, os: macos-latest, flags: "-DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64" },
          ]
        target-type: [template_debug]
        #, template_release]
        float-precision: [single]
        projectdir: [../../project]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch godot-cpp submodule
        run: |
          git submodule update --init --recursive --depth 1 godot-cpp

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      # Setup the compiler environment specifically for Windows/MSVC
      - name: Set up MSVC Developer Command Prompt
        if: ${{ matrix.target.platform == 'windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      # Build GDExtension (with caches)

      - name: Setup Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
          variant: sccache # Required for MSVC/Windows compiler caching tracking

      - name: Configure CMake
        shell: bash
        run: |
          # Map Godot's build types (template, debug, release_debug) to CMake configurations
          if [ "${{ matrix.target-type }}" = "template_release" ]; then
            BUILD_TYPE="Release"
          else
            BUILD_TYPE="Debug"
          fi
          
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache \
            -DGD_ARCH=${{ matrix.target.arch }} \
            -DGD_PRECISION=${{ matrix.float-precision }} \
            -DGD_PROJECT_DIR=${{ matrix.projectdir }} \
             ${{ matrix.target.flags }}

      - name: Build GDExtension via CMake
        shell: bash
        run: |
          if [ "${{ matrix.target-type }}" = "template_release" ]; then
            BUILD_TYPE="Release"
          else
            BUILD_TYPE="Debug"
          fi
          cmake --build build --config $BUILD_TYPE

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot_dev-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/project/bin/**

  # Merges all the build artifacts together into a single godot_dev artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: godot_dev
          pattern: godot_dev-*
          delete-merged: true
